version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    image: backend:latest
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    image: frontend:latest