version: "3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    container_name: frontend     