FROM python:3.8-alpine
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY Pipfile Pipfile.lock /code/
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile
COPY . /code/
CMD ["gunicorn", "backend.wsgi", "--bind", "0.0.0.0:$PORT"]