FROM python
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY Pipfile Pipfile.lock /code/
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile
COPY . /code/
CMD /bin/bash -c "gunicorn backend.wsgi --bind 0.0.0.0:'$PORT'"