# Generated by Django 3.1.7 on 2021-03-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200819_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date_time']},
        ),
    ]
