# Generated by Django 3.1.7 on 2021-03-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_game_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='location_object',
            new_name='location',
        ),
    ]
