# Generated by Django 3.1.7 on 2021-03-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20210323_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentitem',
            options={'ordering': ['post__game__date_time', 'post__role__pk']},
        ),
    ]
