# Generated by Django 3.1.7 on 2021-04-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20210323_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentitem',
            options={'ordering': ['post__game__date_time', 'post__game__pk']},
        ),
    ]
