# Generated by Django 3.1.7 on 2021-04-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_specialblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialblock',
            options={'ordering': ['start']},
        ),
    ]
